name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t myapp .

      - name: Run tests in Docker container
        run: |
          docker run --name myapp-container -d myapp
          docker exec myapp-container pip install pytest
          docker exec myapp-container pytest /app/tests --timeout=30
          test_exit_code=$?
          if [ $test_exit_code -eq 0 ]; then
            echo "Tests passed"
            docker stop myapp-container
            docker rm myapp-container
            exit 0
          else
            echo "Tests failed"
            docker stop myapp-container
            docker rm myapp-container
            exit 1
          fi
