name: Flappy Bird Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t flappybird-app -f Dockerfile .

    - name: Run Docker Container
      run: |
        docker run -d --name flappybird-container flappybird-app
        sleep 1m

    - name: Stop and Remove Docker Container
      run: docker stop flappybird-container && docker rm flappybird-container
